version: "3"

services:
  app:
    image: bw-devops-exercise

  nginx:
    image: nginx
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
