name: Build and push image to CR
# run-name: 

on: 
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions?checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Builx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $${{ secrets.DOCKERHUB_USERNAME }}/bw-devops-exercise:latest
